spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root1234
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8760/eureka
server:
  port: 8080

